In [3]:
import pandas as pd
import numpy as np

#pip install kagglehub

import kagglehub
import kaggle

In [2]:
# Do this in the terminal/ask Copilot

# kaggle competitions files -c nfl-big-data-bowl-2027
# New-Item -ItemType Directory -Force -Path .\data
# kaggle competitions download -c nfl-big-data-bowl-2027 -p .\data
# Expand-Archive .\data\nfl-big-data-bowl-2027.zip -DestinationPath .\data -Force

# Should add the data locally to "data" folder, convert to parquet

In [3]:
# Data

file_path = "C:\\Users\\rschw\\OneDrive\\Desktop\\Big Data Bowl\\NFL_BigData_2027\\data\\nfl-big-data-bowl-2027\\"


combine_results = pd.read_parquet(file_path + "combine_results.parquet")
combine_tracking = pd.read_parquet(file_path + "combine_tracking.parquet")
game_tracking_2023 = pd.read_parquet(file_path + "game_tracking_2023.parquet")
game_tracking_2024 = pd.read_parquet(file_path + "game_tracking_2024.parquet")
game_tracking_2025 = pd.read_parquet(file_path + "game_tracking_2025.parquet")
games = pd.read_parquet(file_path + "games.parquet")
player_career_successes = pd.read_parquet(file_path + "player_career_successes.parquet")
player_plays = pd.read_parquet(file_path + "player_play.parquet")
players = pd.read_parquet(file_path + "players.parquet")

In [4]:
combine_results.head()

,draft_year,nfl_id,combine_position,combine_height,combine_weight,hand_size,arm_length,wing_span,ten_yd_split,forty,vertical,broad_jump,three_cone,short_shuttle,bench_reps,ngs_athleticism_score,ngs_college_production_score,ngs_final_score
0,2023,56040,TE,77.875,245,10.000,32.250,79.750,1.60,4.84,38.5,125.0,NaN,NaN,NaN,60,NaN,NaN
1,2023,56010,DB,70.625,191,8.750,29.625,72.250,1.58,4.59,33.5,116.0,NaN,NaN,23.0,60,77.0,74.0
2,2023,56085,TE,79.375,255,10.250,34.000,83.125,1.57,4.55,40.0,128.0,6.87,4.12,23.0,97,65.0,79.0
3,2023,56056,WR,72.250,192,9.625,31.875,76.125,1.51,4.33,NaN,NaN,NaN,NaN,NaN,76,68.0,73.0
4,2023,56118,WR,71.625,191,9.500,31.000,75.000,1.52,4.54,38.5,120.0,6.98,4.15,14.0,65,65.0,64.0

In [5]:
combine_tracking.head()

,draft_year,event_id,nfl_id,entity_type,time,drill_type,drill_name,attempt,x,y,s,a,dis,dir
0,2025,20250302100900_1740941802777_000,58286,PLAYER,2025-03-02T18:56:38.200,SKILL_DRILLS_OL,OL_PULL_DRILL_FOLD_BLOCK_RIGHT,4,44.785924,28.285528,0.220828,0.682443,0.011085,250.278576
1,2025,20250302100900_1740941802777_000,58286,PLAYER,2025-03-02T18:56:38.300,SKILL_DRILLS_OL,OL_PULL_DRILL_FOLD_BLOCK_RIGHT,4,44.723780,28.297391,0.332931,0.619551,0.003864,257.319206
2,2025,20250302100900_1740941802777_000,58286,PLAYER,2025-03-02T18:56:38.400,SKILL_DRILLS_OL,OL_PULL_DRILL_FOLD_BLOCK_RIGHT,4,44.632680,28.279528,0.481838,0.596455,0.008305,253.176813
3,2025,20250302100900_1740941802777_000,58286,PLAYER,2025-03-02T18:56:38.500,SKILL_DRILLS_OL,OL_PULL_DRILL_FOLD_BLOCK_RIGHT,4,44.544022,28.243767,0.599350,0.664436,0.007964,247.044153
4,2025,20250302100900_1740941802777_000,58286,PLAYER,2025-03-02T18:56:38.600,SKILL_DRILLS_OL,OL_PULL_DRILL_FOLD_BLOCK_RIGHT,4,44.471466,28.210294,0.657540,0.908250,0.005382,240.622668

In [ ]:
player_plays.head()

,game_id,play_id,team_abbr,nfl_id,lined_up_position,play_description,quarter,down,yards_to_go,possession_team,...,sack,tackle,assist,caused_forced_fumble,recovered_fumble,tackle_for_loss,time_to_pressure,time_to_qb_hurry,coverage_assignment,coverage_assignment_at_snap
0,2025111610,2279,BAL,57183,T,(8:42) (Shotgun) L.Jackson pass incomplete dee...,3,1,10,BAL,...,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN
1,2026011701,1626,SF,58248,INTERIOR_LINE,(3:48) (Shotgun) K.Walker left end to SEA 28 f...,2,2,7,SEA,...,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN
2,2025101900,2838,LAR,57140,EDGE,(7:01) C.Van Lanen reported in as eligible. T...,3,2,2,JAX,...,0.0,NaN,NaN,NaN,None,None,NaN,NaN,NO_ASSIGNMENT,NO_ASSIGNMENT
3,2025111300,2628,NYJ,58209,T,(4:05) I.Williams left end to NE 22 for 4 yard...,3,1,10,NYJ,...,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN
4,2025121406,2653,NYG,57191,OLB,"(10:08) (No Huddle, Shotgun) M.Mariota scrambl...",3,2,10,WAS,...,0.0,1.0,0.0,0.0,None,False,NaN,NaN,HOOK_CURL_LEFT,CURL_FLAT_LEFT

:

In [9]:
data = pd.read_csv(r"C:\Users\rschw\OneDrive\Desktop\Big Data Bowl\NFL_BigData_2027\outputs\wr_predictive_redraft.csv")

In [13]:
data.head(15)

,nfl_id,display_name,draft_year,draft_overall_pick,combine_position,combine_height,combine_weight,forty,ten_yd_split,vertical,...,predicted_rookie_yards_combine_only,predicted_rank_combine_only,prediction_error_yards_combine_only,predicted_rookie_yards_combine_plus_movement,predicted_rank_combine_plus_movement,prediction_error_yards_combine_plus_movement,rank_change_vs_draft_order_mean,rank_change_vs_draft_order_draft_pick,rank_change_vs_draft_order_combine_only,rank_change_vs_draft_order_combine_plus_movement
0,57152,Ricky Pearsall,2024,31.0,WR,73.000,189.0,4.41,1.57,42.0,...,892.941216,1.0,492.941216,676.066596,1.0,276.066596,-13.0,-1.332268e-15,2.0,2.000000e+00
1,57263,Anthony Gould,2024,142.0,WR,68.375,174.0,4.39,1.49,39.5,...,604.168066,2.0,581.168066,311.923423,2.0,288.923423,1.0,-4.000000e+00,15.0,1.500000e+01
2,57304,Malik Washington,2024,184.0,WR,68.500,191.0,4.47,1.53,42.5,...,417.473957,3.0,194.473957,280.629830,3.0,57.629830,5.0,-4.000000e+00,18.0,1.800000e+01
3,57234,Devontez Walker,2024,113.0,WR,73.500,193.0,4.36,1.54,40.5,...,241.815067,5.0,220.815067,216.477160,4.0,195.477160,-1.0,1.776357e-15,10.0,1.100000e+01
4,57565,Isaiah Williams,2024,NaN,WR,69.250,182.0,4.63,1.59,38.0,...,242.807463,4.0,236.807463,198.878108,5.0,192.878108,12.0,1.050000e+01,24.0,2.300000e+01
5,57223,Troy Franklin,2024,102.0,WR,73.875,176.0,4.41,1.61,39.0,...,148.919531,6.0,-114.080469,176.674397,6.0,-86.325603,-3.0,0.000000e+00,7.0,7.000000e+00
6,57256,Jacob Cowing,2024,135.0,WR,68.375,168.0,4.38,1.54,36.0,...,147.013099,7.0,67.013099,161.956986,7.0,81.956986,0.0,-4.000000e+00,9.0,9.000000e+00
7,57173,Adonai Mitchell,2024,52.0,WR,74.250,205.0,4.34,1.52,39.5,...,122.824959,10.0,-189.175041,160.213241,8.0,-151.786759,-8.0,1.776357e-15,-2.0,1.776357e-15
8,57361,Tahj Washington,2024,241.0,WR,69.750,174.0,NaN,NaN,35.0,...,137.151538,9.0,137.151538,158.824560,9.0,158.824560,10.0,-4.000000e+00,17.0,1.700000e+01
9,57201,Jermaine Burton,2024,80.0,WR,72.250,196.0,4.45,1.53,38.5,...,140.696905,8.0,33.696905,154.450104,10.0,47.450104,-7.0,-1.776357e-15,1.0,-1.000000e+00
10,57336,Ryan Flournoy,2024,216.0,WR,72.750,202.0,4.44,1.53,39.5,...,111.898832,11.0,9.898832,136.508342,11.0,34.508342,7.0,-4.000000e+00,12.0,1.200000e+01
11,57606,Jalen Coker,2024,NaN,WR,73.375,208.0,4.57,1.52,42.5,...,94.313294,13.0,-383.686706,104.004631,12.0,-373.995369,13.0,1.150000e+01,16.0,1.700000e+01
12,57205,Roman Wilson,2024,84.0,WR,70.750,185.0,4.39,1.52,NaN,...,92.188119,14.0,92.188119,93.709628,13.0,93.709628,-6.0,0.000000e+00,-4.0,-3.000000e+00
13,57158,Ja'Lynn Polk,2024,37.0,WR,73.375,203.0,4.52,1.52,37.5,...,49.333770,20.0,-37.666230,81.703527,14.0,-5.296473,-9.0,0.000000e+00,-13.0,-7.000000e+00
14,57130,Rome Odunze,2024,9.0,WR,74.875,212.0,4.45,1.52,39.0,...,40.174184,22.0,-693.825816,70.078485,15.0,-663.921515,-15.0,0.000000e+00,-21.0,-1.400000e+01